name: Example workflow for Maven using Snyk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup jdk 11
        uses: snyk/actions/maven@master
        with:
         java-version: '11'
         distrivution: 'temurin'
         cache: maven
      - name: Build with Mavencloud
        run: mvn -B verify sonar:sonar -Dsonar.projectkey=asheeshkumartripathi_java-reachability-playground -Dsonar.organization=asheeshkumartripathi -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
